package co.yap.yapcore.constants

object RequestCodes {
    const val REQUEST_CODE_FINISH = "10000"
    const val REQUEST_TOP_UP_BENEFICIARY = 10001
    const val REQUEST_SHOW_BENEFICIARY = 10002
    const val REQUEST_TRANSFER_MONEY = 10003
    const val REQUEST_NOTIFY_BENEFICIARY_LIST = 10004
    const val REQUEST_ADD_FUNDS_WHEN_ADD = 10005
    const val REQUEST_FOR_LOCATION = 10006
    const val REQUEST_REORDER_CARD = 10007
    const val REQUEST_TXN_FILTER = 10008
    const val REQUEST_KYC_DOCUMENTS = 10009
    const val REQUEST_ADD_HOUSE_HOLD = 10010
    const val REQUEST_FOR_GPS = 10011
    const val REQUEST_MEETING_CONFIRMED = 10012
    const val REQUEST_LOCATION_FOR_KYC = 10013
    const val REQUEST_FOR_SET_PIN = 10014
    const val REQUEST_FOR_CURRENCY_SELECTED = 10015
    const val REQUEST_FOR_TRANSACTION_NOTE_ADD_EDIT = 10016
    const val REQUEST_FOR_ADDITIONAL_REQUIREMENT = 10017
    const val REQUEST_Y2Y_TRANSFER: Int = 10018
    const val REQUEST_NOTIFICATION_FLOW: Int = 10019
    const val REQUEST_CARD_ADDED: Int = 10020
    const val REQUEST_CODE_CREATE_PASSCODE: Int = 10021
    const val REQUEST_CODE_MORE_ACTIVITY: Int = 10022
    const val REQUEST_CAMERA_PERMISSION: Int = 10023
    const val REQUEST_ADD_RECEIPT = 10024
    const val REQUEST_DELETE_RECEIPT = 10025
    const val REQUEST_STORAGE_PERMISSION: Int = 10026
    const val REQUEST_NOTIFICATION_SETTINGS: Int = 10026
}