package co.yap.yapcore.enums

enum class AccountStatus {
    ON_BOARDED,
    MEETING_SCHEDULED,
    MEETING_SUCCESS,
    CAPTURED_EID,
    EID_EXPIRED,
    EID_UPDATED,
    EID_RESCAN_REQ,
    EID_FAILED,
    REJECTED,
    MEETING_FAILED,
    SOFT_KYC_DONE,
    SOFT_KYC_FAILED,
    PHYSICAL_CARD_ORDERED,
    CARD_ACTIVATED,
    PARNET_MOBILE_VERIFICATION_PENDING,
    PASS_CODE_PENDING,
    EMAIL_PENDING,
    BIRTH_INFO_COLLECTED,
    FATCA_GENERATED,
    CAPTURED_ADDRESS,
    INVITATION_PENDING;

}