package co.yap.yapcore.enums

import androidx.annotation.Keep

@Keep
enum class NotificationStatus {
    ON_BOARDED,
    MEETING_SCHEDULED,
    BIRTH_INFO_COLLECTED,
    FATCA_GENERATED,
    MEETING_SUCCESS,
    MEETING_FAILED,
    CAPTURED_EID,
    CAPTURED_ADDRESS,
    CARD_ACTIVATED,
    PARNET_MOBILE_VERIFICATION_PENDING,
    PASS_CODE_PENDING,
    EID_RESCAN_REQ,
    EMAIL_PENDING,
    WORKITEM_GENERATION_FAILED,
    INVESTIGATION_REQ,
    PROCESSING_AT_BANK,
    FIRST_KYC_FAILED,
    SECOND_KYC_FAILED,
    ADDITIONAL_COMPLIANCE_INFO_REQ,
    ADD_INFO_NOTIFICATION_DONE,
    ADDITIONAL_COMPLIANCE_INFO_PROVIDED,
    ADD_COMPLIANCE_INFO_SUBMITTED_BY_ADMIN,
    EMP_INFO_COMPLETED

}
